version: "3.9"
services:
  db:
    image: postgres:12.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
    env_file:
      - .env

  redis:
    image: redis:5.0.7-alpine
    command: redis-server --appendonly yes  # enable persistent storage
    volumes:
      - redisdata:/data
    env_file:
      - .env

  sidekiq:
    depends_on:
      - redis
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/myapp
    env_file:
      - .env

  web:
    build: .
    volumes:
      - .:/myapp
    ports:
      - 3000:3000
    depends_on:
      - db
      - sidekiq
    env_file:
      - .env

volumes:
  postgres_data:
  redisdata:
    driver: local
