default: &default
  adapter: postgresql
  host: <%= ENV['POSTGRES_HOST'] || 'localhost' %>
  port: <%= ENV['POSTGRES_PORT'] || 5432 %>
  pool: <%= ENV['POSTGRES_POOL'] || 5 %>
  encoding: unicode
  username: <%= ENV['POSTGRES_USERNAME'] || 'postgres' %>
  password: <%= ENV['POSTGRES_PASSWORD'] || 'postgres' %>
  sslmode: disable

development:
  <<: *default
  database: leaderboard_dev

test:
  <<: *default
  database: leaderboard_test

production:
  adapter: postgresql
  encoding: unicode
  timeout: 5000
  pool: <%= ENV['POSTGRES_POOL'] || 5 %>
  database: leaderboard_production
  username: <%= ENV['POSTGRES_USERNAME'] || 'postgres' %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket: "/cloudsql/leaderboard-382013:us-central1:leaderboard"
