# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

if Country.count.zero?
  Country.create(name: 'Afghanistan')
  Country.create(name: 'Antigua and Barbuda')
  Country.create(name: 'Anguilla')
  Country.create(name: 'Albania')
  Country.create(name: 'Armenia')
  Country.create(name: 'Antarctica')
  Country.create(name: 'Argentina')
  Country.create(name: 'American Samoa')
  Country.create(name: 'Austria')
  Country.create(name: 'Australia')
  Country.create(name: 'Aruba')
  Country.create(name: 'Bosnia and Herzegovina')
  Country.create(name: 'Barbados')
  Country.create(name: 'Bangladesh')
  Country.create(name: 'Belgium')
  Country.create(name: 'Burkina Faso')
  Country.create(name: 'Burundi')
  Country.create(name: 'Benin')
  Country.create(name: 'Bermuda')
  Country.create(name: 'Brunei')
  Country.create(name: 'Brazil')
  Country.create(name: 'Bahamas')
  Country.create(name: 'Bhutan')
  Country.create(name: 'Bouvet Island')
  Country.create(name: 'Botswana')
  Country.create(name: 'Belize')
  Country.create(name: 'Canada')
  Country.create(name: 'Congo [DRC]')
  Country.create(name: 'Congo [Republic]')
  Country.create(name: 'Switzerland')
  Country.create(name: 'Cook Islands')
  Country.create(name: 'Chile')
  Country.create(name: 'Cameroon')
  Country.create(name: 'China')
  Country.create(name: 'Colombia')
  Country.create(name: 'Cuba')
  Country.create(name: 'Cape Verde')
  Country.create(name: 'Christmas Island')
  Country.create(name: 'Cyprus')
  Country.create(name: 'Germany')
  Country.create(name: 'Denmark')
  Country.create(name: 'Dominica')
  Country.create(name: 'Dominican Republic')
  Country.create(name: 'Algeria')
  Country.create(name: 'Estonia')
  Country.create(name: 'Egypt')
  Country.create(name: 'Western Sahara')
  Country.create(name: 'Eritrea')
  Country.create(name: 'Spain')
  Country.create(name: 'Finland')
  Country.create(name: 'Fiji')
  Country.create(name: 'Faroe Islands')
  Country.create(name: 'France')
  Country.create(name: 'Gabon')
  Country.create(name: 'United Kingdom')
  Country.create(name: 'Grenada')
  Country.create(name: 'Georgia')
  Country.create(name: 'French Guiana')
  Country.create(name: 'Ghana')
  Country.create(name: 'Gibraltar')
  Country.create(name: 'Greenland')
  Country.create(name: 'Gambia')
  Country.create(name: 'Equatorial Guinea')
  Country.create(name: 'Greece')
  Country.create(name: 'Guatemala')
  Country.create(name: 'Guam')
  Country.create(name: 'Guinea-Bissau')
  Country.create(name: 'Guyana')
  Country.create(name: 'Gaza Strip')
  Country.create(name: 'Hong Kong')
  Country.create(name: 'Honduras')
  Country.create(name: 'Angola')
  Country.create(name: 'Indonesia')
  Country.create(name: 'Israel')
  Country.create(name: 'India')
  Country.create(name: 'British Indian Ocean Territory')
  Country.create(name: 'Iraq')
  Country.create(name: 'Iran')
  Country.create(name: 'Iceland')
  Country.create(name: 'Jersey')
  Country.create(name: 'Jamaica')
  Country.create(name: 'Jordan')
  Country.create(name: 'Japan')
  Country.create(name: 'Kyrgyzstan')
  Country.create(name: 'Kiribati')
  Country.create(name: 'Comoros')
  Country.create(name: 'North Korea')
  Country.create(name: 'South Korea')
  Country.create(name: 'Kuwait')
  Country.create(name: 'Cayman Islands')
  Country.create(name: 'Kazakhstan')
  Country.create(name: 'Laos')
  Country.create(name: 'Lebanon')
  Country.create(name: 'Liechtenstein')
  Country.create(name: 'Sri Lanka')
  Country.create(name: 'Lesotho')
  Country.create(name: 'Lithuania')
  Country.create(name: 'Latvia')
  Country.create(name: 'Libya')
  Country.create(name: 'Morocco')
  Country.create(name: 'Monaco')
  Country.create(name: 'Moldova')
  Country.create(name: 'Madagascar')
  Country.create(name: 'Marshall Islands')
  Country.create(name: 'Macedonia [FYROM]')
  Country.create(name: 'Mali')
  Country.create(name: 'Macau')
  Country.create(name: 'Northern Mariana Islands')
  Country.create(name: 'Martinique')
  Country.create(name: 'Mauritania')
  Country.create(name: 'Montserrat')
  Country.create(name: 'Mauritius')
  Country.create(name: 'Maldives')
  Country.create(name: 'Malawi')
  Country.create(name: 'Mexico')
  Country.create(name: 'Malaysia')
  Country.create(name: 'Namibia')
  Country.create(name: 'Niger')
  Country.create(name: 'Norfolk Island')
  Country.create(name: 'Nigeria')
  Country.create(name: 'Netherlands')
  Country.create(name: 'Norway')
  Country.create(name: 'Nepal')
  Country.create(name: 'Nauru')
  Country.create(name: 'Niue')
  Country.create(name: 'Oman')
  Country.create(name: 'Panama')
  Country.create(name: 'Peru')
  Country.create(name: 'Papua New Guinea')
  Country.create(name: 'Pakistan')
  Country.create(name: 'Poland')
  Country.create(name: 'Saint Pierre and Miquelon')
  Country.create(name: 'Pitcairn Islands')
  Country.create(name: 'Puerto Rico')
  Country.create(name: 'Portugal')
  Country.create(name: 'Palau')
  Country.create(name: 'Paraguay')
  Country.create(name: 'Qatar')
  Country.create(name: 'RZunion')
  Country.create(name: 'Romania')
  Country.create(name: 'Russia')
  Country.create(name: 'Saudi Arabia')
  Country.create(name: 'Solomon Islands')
  Country.create(name: 'Bahrain')
  Country.create(name: 'United Arab Emirates')
  Country.create(name: 'Netherlands Antilles')
  Country.create(name: 'Azerbaijan')
  Country.create(name: 'Bulgaria')
  Country.create(name: 'Bolivia')
  Country.create(name: 'Belarus')
  Country.create(name: 'Central African Republic')
  Country.create(name: 'Costa Rica')
  Country.create(name: 'Ecuador')
  Country.create(name: 'Ethiopia')
  Country.create(name: 'Falkland Islands [Islas Malvinas]')
  Country.create(name: 'Guernsey')
  Country.create(name: 'Guadeloupe')
  Country.create(name: 'South Georgia and the South Sandwich Islands')
  Country.create(name: 'Croatia')
  Country.create(name: 'Haiti')
  Country.create(name: 'Isle of Man')
  Country.create(name: 'Italy')
  Country.create(name: 'Kenya')
  Country.create(name: 'Saint Lucia')
  Country.create(name: 'Luxembourg')
  Country.create(name: 'Montenegro')
  Country.create(name: 'Myanmar [Burma]')
  Country.create(name: 'Malta')
  Country.create(name: 'Mozambique')
  Country.create(name: 'Nicaragua')
  Country.create(name: 'New Zealand')
  Country.create(name: 'Philippines')
  Country.create(name: 'Palestinian Territories')
  Country.create(name: 'Serbia')
  Country.create(name: 'Seychelles')
  Country.create(name: 'Sudan')
  Country.create(name: 'Sweden')
  Country.create(name: 'Singapore')
  Country.create(name: 'Slovenia')
  Country.create(name: 'Svalbard and Jan Mayen')
  Country.create(name: 'Slovakia')
  Country.create(name: 'Sierra Leone')
  Country.create(name: 'San Marino')
  Country.create(name: 'Somalia')
  Country.create(name: 'Suriname')
  Country.create(name: "S TomZ and Pr'ncipe")
  Country.create(name: 'El Salvador')
  Country.create(name: 'Syria')
  Country.create(name: 'Chad')
  Country.create(name: 'French Southern Territories')
  Country.create(name: 'Togo')
  Country.create(name: 'Thailand')
  Country.create(name: 'Tokelau')
  Country.create(name: 'Timor-Leste')
  Country.create(name: 'Turkmenistan')
  Country.create(name: 'Tunisia')
  Country.create(name: 'Tonga')
  Country.create(name: 'Trinidad and Tobago')
  Country.create(name: 'Tuvalu')
  Country.create(name: 'Taiwan')
  Country.create(name: 'Tanzania')
  Country.create(name: 'Ukraine')
  Country.create(name: 'U.S. Minor Outlying Islands')
  Country.create(name: 'Uruguay')
  Country.create(name: 'Uzbekistan')
  Country.create(name: 'Vatican City')
  Country.create(name: 'Venezuela')
  Country.create(name: 'British Virgin Islands')
  Country.create(name: 'U.S. Virgin Islands')
  Country.create(name: 'Vietnam')
  Country.create(name: 'Vanuatu')
  Country.create(name: 'Wallis and Futuna')
  Country.create(name: 'Kosovo')
  Country.create(name: 'Yemen')
  Country.create(name: 'Mayotte')
  Country.create(name: 'Zambia')
  Country.create(name: 'Cocos [Keeling] Islands')
  Country.create(name: 'Djibouti')
  Country.create(name: 'Micronesia')
  Country.create(name: 'Guinea')
  Country.create(name: 'Heard Island and McDonald Islands')
  Country.create(name: 'Hungary')
  Country.create(name: 'Ireland')
  Country.create(name: 'Cambodia')
  Country.create(name: 'Liberia')
  Country.create(name: 'Mongolia')
  Country.create(name: 'New Caledonia')
  Country.create(name: 'French Polynesia')
  Country.create(name: 'Rwanda')
  Country.create(name: 'Andorra')
  Country.create(name: 'Czech Republic')
  Country.create(name: 'Saint Kitts and Nevis')
  Country.create(name: 'Saint Helena')
  Country.create(name: 'Turks and Caicos Islands')
  Country.create(name: 'United States')
  Country.create(name: 'South Africa')
  Country.create(name: 'Senegal')
  Country.create(name: 'Swaziland')
  Country.create(name: 'Tajikistan')
  Country.create(name: 'Turkey')
  Country.create(name: 'Uganda')
  Country.create(name: 'Saint Vincent and the Grenadines')
  Country.create(name: 'Samoa')
  Country.create(name: 'Zimbabwe')
end

if Rails.env.development? && AdminUser.count.zero?
  AdminUser.create!(
    email: 'admin@example.com',
    password: ENV['ADMIN_PASSWORD'],
    password_confirmation: ENV['ADMIN_PASSWORD']
  )
end
